# -*- coding: utf-8 -*-
"""sentiment.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1bxPjM9SRHlZfgCZ-69JeaaclGsZ4y7jM

Este notebook executa uma análise de sentimentos para identificar a percepção do público sobre clubes de futebol ingleses, com base em textos retirados de redes sociais.
"""

!pip install -U pip setuptools wheel
!pip install -U spacy==3.5.2
!python -m spacy download en_core_web_sm
!pip install spacytextblob==4.0.0

import pkg_resources, imp
imp.reload(pkg_resources)

"""Importando as bibliotecas para análise de sentimento"""

import spacy
from spacytextblob.spacytextblob import SpacyTextBlob

"""Definindo o modelo e a pipeline a serem utilizadas na análise"""

nlp = spacy.load('en_core_web_sm')
nlp.add_pipe('spacytextblob')

"""Definindo o texto inicial a ser analisado para verificação/validação da biblioteca"""

user_input = "This is a wonderful campsite. I loved the serenity and the birds chirping in the morning."
doc = nlp(user_input)

"""Exibindo o resultado da primeira análise (um range entre -1 [avaliação negativa] e 1 [avaliação positiva])[texto do link](https://)"""

input_polarity = doc._.polarity
sentiment = {
    'score': input_polarity
}

print(sentiment)

"""Definindo a lista de tweets a serem analisadas"""

tweets = [
    "Bayer Leverkusen goalkeeper Bernd Leno will not be going to Napoli...",
    "Gary Speed v Blackburn at St James in 2001/02 anyone?",
    "@ChelseaFC Don't make him regret it and start him over Hoofiz",
    "@LiverpoolFF @AnfieldEdition He's a liar, made up. I've unfollowed him...",
    "@theesk @Everton Didn't realise Kenwright is due to leave...",
    "@hasanshahbaz19 @LFC My knowledge has decreased somewhat in the past few seasons",
    "Report: Linked with #Everton and #Wolves, Italians set to sign £4.5m-rated winger",
    "Am seeing tweets that there’s been a fall out @Everton...",
    "@LFC @officialAL20 @IntChampionsCup @ManUtd Expect loads of excuses after tonight’s game",
    "Pogba scores, Pogba assists. But tomorrow papers won't be telling you this..."
]

"""Analisando os tweets"""

for item in tweets:
    doc = nlp(item)
    input_polarity = doc._.polarity
    sentiment = {
        'tweet': item,
        'score': input_polarity
    }
    print(sentiment)